// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from minimal-gir
// DO NOT EDIT

use crate::{ffi,Extensible};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "EExtension")]
    pub struct Extension(Object<ffi::EExtension, ffi::EExtensionClass>);

    match fn {
        type_ => || ffi::e_extension_get_type(),
    }
}

impl Extension {
        pub const NONE: Option<&'static Extension> = None;
    
}

pub trait ExtensionExt: IsA<Extension> + 'static {
    #[doc(alias = "e_extension_get_extensible")]
    #[doc(alias = "get_extensible")]
    fn extensible(&self) -> Option<Extensible> {
        unsafe {
            from_glib_none(ffi::e_extension_get_extensible(self.as_ref().to_glib_none().0))
        }
    }
}

impl<O: IsA<Extension>> ExtensionExt for O {}
