// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from minimal-gir
// DO NOT EDIT

use crate::{ffi,Extension};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "EExtensible")]
    pub struct Extensible(Interface<ffi::EExtensible, ffi::EExtensibleInterface>);

    match fn {
        type_ => || ffi::e_extensible_get_type(),
    }
}

impl Extensible {
        pub const NONE: Option<&'static Extensible> = None;
    
}

pub trait ExtensibleExt: IsA<Extensible> + 'static {
    #[doc(alias = "e_extensible_load_extensions")]
    fn load_extensions(&self) {
        unsafe {
            ffi::e_extensible_load_extensions(self.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "e_extensible_reload_extensions")]
    fn reload_extensions(&self) {
        unsafe {
            ffi::e_extensible_reload_extensions(self.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "e_extensible_list_extensions")]
    fn list_extensions(&self, extension_type: glib::types::Type) -> Vec<Extension> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::e_extensible_list_extensions(self.as_ref().to_glib_none().0, extension_type.into_glib()))
        }
    }
}

impl<O: IsA<Extensible>> ExtensibleExt for O {}
