// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from minimal-gir
// DO NOT EDIT

mod extensible;
pub use self::extensible::Extensible;

mod extension;
pub use self::extension::Extension;

pub(crate) mod traits {
    pub use super::extensible::ExtensibleExt;
    pub use super::extension::ExtensionExt;
}
