// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from minimal-gir
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "EExtensibleInterface", sizeof(EExtensibleInterface), alignof(EExtensibleInterface));
    printf("%s;%zu;%zu\n", "EExtension", sizeof(EExtension), alignof(EExtension));
    printf("%s;%zu;%zu\n", "EExtensionClass", sizeof(EExtensionClass), alignof(EExtensionClass));
    return 0;
}
