// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from minimal-gir
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal, clippy::upper_case_acronyms)]
#![cfg_attr(docsrs, feature(doc_cfg))]


#[allow(unused_imports)]
use std::ffi::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong, c_void};
#[allow(unused_imports)]
use libc::{size_t, ssize_t, time_t, off_t, intptr_t, uintptr_t, FILE};
#[cfg(unix)]
#[allow(unused_imports)]
use libc::{dev_t, gid_t, pid_t, socklen_t, uid_t};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Records
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EExtensibleInterface {
    pub parent_interface: gobject::GTypeInterface,
}

impl ::std::fmt::Debug for EExtensibleInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("EExtensibleInterface @ {self:p}"))
         .field("parent_interface", &self.parent_interface)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct EExtensionClass {
    pub parent_class: gobject::GObjectClass,
    pub extensible_type: GType,
}

impl ::std::fmt::Debug for EExtensionClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("EExtensionClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .field("extensible_type", &self.extensible_type)
         .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _EExtensionPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type EExtensionPrivate = _EExtensionPrivate;

// Classes
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EExtension {
    pub parent: gobject::GObject,
    pub priv_: *mut EExtensionPrivate,
}

impl ::std::fmt::Debug for EExtension {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("EExtension @ {self:p}"))
         .finish()
    }
}

// Interfaces
#[repr(C)]
#[allow(dead_code)]
pub struct EExtensible {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for EExtensible {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "EExtensible @ {self:p}")
    }
}


unsafe extern "C" {

    //=========================================================================
    // EExtension
    //=========================================================================
    pub fn e_extension_get_type() -> GType;
    pub fn e_extension_get_extensible(extension: *mut EExtension) -> *mut EExtensible;

    //=========================================================================
    // EExtensible
    //=========================================================================
    pub fn e_extensible_get_type() -> GType;
    pub fn e_extensible_load_extensions(extensible: *mut EExtensible);
    pub fn e_extensible_reload_extensions(extensible: *mut EExtensible);
    pub fn e_extensible_list_extensions(extensible: *mut EExtensible, extension_type: GType) -> *mut glib::GList;

}
